### ISSUE TITLE
Type 'Kit' has no member 'createPublicKey'

### ISSUE THREAD

**Issue by aburashima** [horizontalsystems/hd-wallet-kit-ios#26]
HDPublicKit class has method
    static func from(privateKey raw: Data, compression: Bool = false) -> Data {
        return Kit.createPublicKey(fromPrivateKeyData: raw, compressed: compression)
    }
but there is no  'createPublicKey' method in Kit class.
Where can it be found?

**Comment by ant013** [comment]
Hi! We transfer all sources to packages. You can found it there. https://github.com/horizontalsystems/HsCryptoKit.Swift/blob/main/Sources/HsCryptoKit/Crypto.swift
For create publicKey data from private we use secp256k1 create method. 
"public static func publicKey(privateKey: Data, compressed: Bool) -> Data"

**Comment by aburashima** [comment]
> Hi! We transfer all sources to packages. You can found it there. https://github.com/horizontalsystems/HsCryptoKit.Swift/blob/main/Sources/HsCryptoKit/Crypto.swift For create publicKey data from private we use secp256k1 create method. "public static func publicKey(privateKey: Data, compressed: Bool) -> Data"

**Comment by aburashima** [comment]
Thanks a lot! I've already found it.
